In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [2]:
dtst=pd.read_csv("C:/Users/PARCHU/Downloads/Credit_Card_Applications (1).csv")

In [3]:
dtst

CustomerID  A1     A2      A3  A4  A5  A6     A7  A8  A9  A10  A11  A12  \
0      15776156   1  22.08  11.460   2   4   4  1.585   0   0    0    1    2   
1      15739548   0  22.67   7.000   2   8   4  0.165   0   0    0    0    2   
2      15662854   0  29.58   1.750   1   4   4  1.250   0   0    0    1    2   
3      15687688   0  21.67  11.500   1   5   3  0.000   1   1   11    1    2   
4      15715750   1  20.17   8.170   2   6   4  1.960   1   1   14    0    2   
..          ...  ..    ...     ...  ..  ..  ..    ...  ..  ..  ...  ...  ...   
685    15808223   1  31.57  10.500   2  14   4  6.500   1   0    0    0    2   
686    15769980   1  20.67   0.415   2   8   4  0.125   0   0    0    0    2   
687    15675450   0  18.83   9.540   2   6   4  0.085   1   0    0    0    2   
688    15776494   0  27.42  14.500   2  14   8  3.085   1   1    1    0    2   
689    15592412   1  41.00   0.040   2  10   4  0.040   0   1    1    0    1   

     A13   A14  Class  
0    100  1213      0  
1    160     1      0  
2    280     1      0  
3      0     1      1  
4     60   159      1  
..   ...   ...    ...  
685    0     1      1  
686    0    45      0  
687  100     1      1  
688  120    12      1  
689  560     1      1  

[690 rows x 16 columns]

In [4]:
train,test=train_test_split(dtst,test_size=0.3)
trainx=train.iloc[:,0:15]
trainy=train.iloc[:,15]
testx=test.iloc[:,0:15]
testy=test.iloc[:,15]

In [5]:
trainx

CustomerID  A1     A2      A3  A4  A5  A6      A7  A8  A9  A10  A11  A12  \
30     15672432   1  27.00   0.750   2   8   8   4.250   1   1    3    1    2   
239    15594133   1  48.33  12.000   2   7   4  16.000   1   0    0    0    1   
301    15788224   1  20.00  11.045   2   8   4   2.000   0   0    0    1    2   
607    15571571   1  39.17   1.625   2   8   4   1.500   1   1   10    0    2   
112    15572390   1  27.83   4.000   1   3   8   5.750   1   1    2    1    2   
..          ...  ..    ...     ...  ..  ..  ..     ...  ..  ..  ...  ...  ...   
482    15778589   1  20.42   0.000   2   8   4   0.000   0   0    0    0    3   
472    15721569   1  23.25   1.500   2  11   4   2.375   1   1    3    1    2   
158    15627699   1  22.67   1.585   1   9   4   3.085   1   1    6    0    2   
47     15737627   1  16.17   0.040   2   8   4   0.040   0   0    0    0    2   
486    15744423   1  57.83   7.040   2   7   4  14.000   1   1    6    1    2   

     A13   A14  
30   312   151  
239  110     1  
301  136     1  
607  186  4701  
112   75     1  
..   ...   ...  
482  184     1  
472    0   583  
158   80     1  
47     0     1  
486  360  1333  

[483 rows x 15 columns]

In [6]:
trainy

30     1
239    1
301    0
607    1
112    0
      ..
482    0
472    1
158    1
47     1
486    1
Name: Class, Length: 483, dtype: int64

In [8]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

In [9]:
pred_gnb=gnb.fit(trainx,trainy).predict(testx)
pred_mnb=mnb.fit(trainx,trainy).predict(testx)
pred_bnb=bnb.fit(trainx,trainy).predict(testx)
cm1=confusion_matrix(testy,pred_gnb)
accgnb=np.mean(pred_gnb==testy.values.flatten())
cm2=confusion_matrix(testy,pred_mnb)
accmnb=np.mean(pred_mnb==testy.values.flatten())
cm3=confusion_matrix(testy,pred_mnb)
accbnb=np.mean(pred_bnb==testy.values.flatten())



In [10]:
cm1

array([[117,   9],
       [ 31,  50]], dtype=int64)

In [11]:
accgnb

0.8067632850241546

In [12]:
cm2

array([[118,   8],
       [ 44,  37]], dtype=int64)

In [13]:
accmnb

0.748792270531401

In [14]:
cm3

array([[118,   8],
       [ 44,  37]], dtype=int64)

In [15]:
accbnb

0.8840579710144928