In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix

In [2]:
dtst=pd.read_csv("C:/Users/PARCHU/Downloads/Multi Linear Regression.csv")

In [3]:
dtst


Customer ID  C1_gender  C1_Umur  C1_Marital  C1_Edu  C1_Occup  \
0     1234561689          2        5           2       2         5   
1     1234561690          2        4           2       3         4   
2     1234561914          1        1           1       4         2   
3     1234561755          1        4           1       2         2   
4     1234561729          2        5           1       2         4   
..           ...        ...      ...         ...     ...       ...   
994   1234561812          2        5           3       1         2   
995   1234561914          1        5           2       3         2   
996   1234561196          1        4           2       2         3   
997   1234561517          1        2           1       1         1   
998   1234561346          2        5           3       1         1   

     C1_HomeStatus  C2_Avgmtd  C2_Avgytd  C3_income  C3_Tenor  C4_Appraisal  \
0                1          3          5          4         3             2   
1                1          5          3          5         5             2   
2                2          3          1          4         4             5   
3                4          3          4          2         1             4   
4                3          4          3          5         1             1   
..             ...        ...        ...        ...       ...           ...   
994              5          4          1          3         2             1   
995              4          1          2          2         5             1   
996              2          1          2          3         2             4   
997              2          4          3          2         2             5   
998              4          1          3          1         1             5   

     C5_Industry  Pelurasan Kredit  
0              3                 1  
1             10                 0  
2              4                 1  
3              8                 1  
4              2                 0  
..           ...               ...  
994            4                 1  
995            3                 0  
996           10                 0  
997            1                 1  
998            4                 1  

[999 rows x 14 columns]

In [4]:
train,test=train_test_split(dtst,test_size=0.3)
trainx=train.iloc[:,0:13]
trainy=train.iloc[:,13]
testx=test.iloc[:,0:13]
testy=test.iloc[:,13]

In [5]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

In [6]:
prd_gnb=gnb.fit(trainx,trainy).predict(testx)
prd_mnb=mnb.fit(trainx,trainy).predict(testx)
prd_bnb=bnb.fit(trainx,trainy).predict(testx)
cm1=confusion_matrix(prd_gnb,testy)
cm2=confusion_matrix(prd_mnb,testy)
cm3=confusion_matrix(prd_bnb,testy)
ac1=np.mean(prd_gnb==testy)
ac2=np.mean(prd_mnb==testy)
ac3=np.mean(prd_bnb==testy)

In [7]:
cm1

array([[78, 78],
       [64, 80]], dtype=int64)

In [8]:
ac1

0.5266666666666666

In [9]:
cm2

array([[78, 85],
       [64, 73]], dtype=int64)

In [10]:
ac2

0.5033333333333333

In [11]:
cm3

array([[142, 158],
       [  0,   0]], dtype=int64)

In [12]:
ac3

0.47333333333333333